export const GALLERY_PARALLAX_IMAGES: string[] = [
  "/assets/event-photos/Beyond DSA/WhatsApp Image 2026-09-28 at 2.40.55 PM.jpeg",
  "/assets/event-photos/HackBPIT 2k23/Square Poster .jpg",
  "/assets/event-photos/Introduction to AI Agents/poster.jpeg",
  "/assets/event-photos/Meet Your Alumni/1.png",
  "/assets/event-photos/Orientation/WhatsApp Image 2026-09-28 at 2.48.05 PM.jpeg",
  "/assets/event-photos/Reforged 26/banner.webp",
  "/assets/event-photos/Techstarter 26/poster.jpg",
  "/assets/event-photos/TechStarter 2k24/image.png",
  "/assets/event-photos/web3 and blockchain 2024/WhatsApp Image 2026-09-28 at 2.40.55 PM.jpeg",
  "/assets/event-photos/archived/Technovation 2k23/2.jpg",
  "/assets/event-photos/archived/Gate Session by Unacademy/image copy.png",
  "/assets/event-photos/archived/Placements @Google/image copy 2.png",
  "/assets/event-photos/archived/Succesfull Engineer ft Fraz/2.png",
  "/assets/event-photos/HackBPIT 2k23/Stage Photo 2.jpg",
  "/assets/event-photos/HackBPIT 2k23/Winner 1.jpg",
];
